# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'MarleySpoonChallengeIlke' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MarleySpoonChallengeIlke
  pod 'Contentful', '~> 5.0.0' , :inhibit_warnings => true
  pod 'Kingfisher' , :inhibit_warnings => true

  target 'MarleySpoonChallengeIlkeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MarleySpoonChallengeIlkeUITests' do
    # Pods for testing
  end

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = "YES"
        end
    end
end
